name: Build and deploy Python project to Azure Function App - vm-fun
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
env:
  PYTHON_VERSION: '3.11'
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
 
      - name: Install dependencies
        run: pip install -r requirements.txt
 
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "venv/*" ".git/*" ".github/*" "*.zip"
 
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
 
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .
 
      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'vm-fun'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_68ED6FA21D164C3ABCB255AF90B73A28 }}
